language: swift
xcode_project: RUCademy.xcodeproj # path to your xcodeproj folder
xcode_scheme: RUCademyTests
script: xcodebuild -workspace RUCademy.xcworkspace -scheme RUCademy -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4' test
before_install:
 - pod repo update
