language: swift
xcode_project: RUCademy.xcodeproj # path to your xcodeproj folder
xcode_scheme: RUCademyTests
script: xcodebuild test -workspace RUCademy.xcworkspace -scheme RUCademyTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
before_install:
 - pod repo update
